### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by andres-blanco** [simplesamlphp/simplesamlphp-module-openidprovider#4]
Hey, is this project still mantained?

**Comment by jaimeperez** [comment]
Hola Andrés,

Considering this module was offering support for OpenID, and not **OpenID Connect**, it shouldn't probably be used at all. The protocol is seldom used nowadays. So I guess the response to your question is then no. We still update it if something breaks, or if the APIs it uses change, but nothing further than that.
