### ISSUE TITLE
[BUG] Remove Include/Classpath issue in composer.json

### ISSUE THREAD

**Issue by mbl-35** [simplesamlphp/simplesamlphp-module-openidprovider#6]
Could you please the openid class load instruction in the composer.json because composer dumpautoload has following error:

```shell
[RuntimeException]
Could not scan for classes inside "xxxxx/vendor/simplesamlphp/simplesamlphp/modules/openidProvider/vendor/openid/php-openid/Auth/" which does not appear to be a file
   nor a folder
```

part of the code in the composer.json:
```json
"classmap": ["vendor/openid/php-openid/Auth/"]
```

Thanks

**Comment by tvdijen** [comment]
dumpautoload works fine, but you have run `composer install` first..

**Comment by tvdijen** [comment]
I'm sorry, I now see what you mean.. Running `composer require` from a simplesamlphp-install will fail with the mentioned exception

**Comment by tvdijen** [comment]
Was fixed in master;  a new release will follow shortly
