### ISSUE TITLE
twig templates missing? 

### ISSUE THREAD

**Issue by alx542** [simplesamlphp/simplesamlphp-module-openidprovider#7]
There seems to be an issue with rendering templates, and maybe the templates are missing from the repo. E.g. where is user.twig ?? 

www/user.php
wants to call  
$t = new \SimpleSAML\XHTML\Template($globalConfig, 'openidProvider:user.twig');
...
$t->send();

Template.php 
send() wants to call getContents() 
which tries to render the template but no luck 

Error\Exception: Error 1 - Call to a member function render() on null at simplesamlphp/lib/SimpleSAML/XHTML/Template.php:514

**Comment by tvdijen** [comment]
They just never have been created.. I guess I've been a bit over-enthousiastic by removing the old templates...

**Comment by tvdijen** [comment]
Just out of curiosity... Why are you still using this ancient protocol?

**Comment by tvdijen** [comment]
I've tagged v1.1.1 with the templates.. I have no way of testing them, so please let me know how things work out

**Comment by DasLampe** [comment]
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 www/_include.php:17 (SimpleSAML_exception_handler)
1 /var/www/foobar/vendor/symfony/error-handler/ErrorHandler.php:599 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Twig\Error\SyntaxError: Unexpected character "$".
Backtrace:
13 modules/openidProvider/templates/user.twig:11 (Twig\Lexer::lexExpression)
12 /var/www/foobar/vendor/twig/twig/src/Lexer.php:281 (Twig\Lexer::lexBlock)
11 /var/www/foobar/vendor/twig/twig/src/Lexer.php:182 (Twig\Lexer::tokenize)
10 /var/www/foobar/vendor/twig/twig/src/Environment.php:542 (Twig\Environment::tokenize)
9 /var/www/foobar/vendor/twig/twig/src/Environment.php:595 (Twig\Environment::compileSource)
8 /var/www/foobar/vendor/twig/twig/src/Environment.php:408 (Twig\Environment::loadClass)
7 /var/www/foobar/vendor/twig/twig/src/Environment.php:381 (Twig\Environment::loadTemplate)
6 /var/www/foobar/vendor/twig/twig/src/Environment.php:359 (Twig\Environment::load)
5 /var/www/foobar/vendor/twig/twig/src/Environment.php:318 (Twig\Environment::render)
4 lib/SimpleSAML/XHTML/Template.php:495 (SimpleSAML\XHTML\Template::getContents)
3 lib/SimpleSAML/XHTML/Template.php:510 (SimpleSAML\XHTML\Template::send)
2 modules/openidProvider/www/user.php:72 (require)
1 lib/SimpleSAML/Module.php:275 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

**Comment by tvdijen** [comment]
That one's covered now

**Comment by DasLampe** [comment]
![image](https://user-images.githubusercontent.com/65374/77537556-98764f80-6e9e-11ea-9eda-a1b93af13efb.png)
Looks like my PR fixed the Twig-Errors but there lot of not replaced vars in the template

**Comment by tvdijen** [comment]
Translations have also been covered

**Comment by tvdijen** [comment]
I was able to test user.php and it seems to work.. Maybe not very pretty, but it works and everything is translated...
The trust-template hasn't been tested, but given the content of the template there's not much that could go wrong..  Let me know if the latest version works for you
