### ISSUE TITLE
case sensitive openidProvider

### ISSUE THREAD

**Issue by alx542** [simplesamlphp/simplesamlphp-module-openidprovider#8]
the namesspace in some files is not consistent with the class names used when instantiating an object.  Possibly you're working in windows and it's not an issue, but in Linux it generates an error.

e.g. in user.php wants to do
   
$server = \SimpleSAML\Module\openidProvider\ProviderServer::getInstance();

but the namespace in /lib/ProviderServer.php  is: 

namespace SimpleSAML\Module\openidprovider;

changing the namespace  to SimpleSAML\Module\openidProvider resolves this error (but there are ones after that when template does not render).

**Comment by tvdijen** [comment]
I can't find any cases of `openidProvider` on master.. Are you perhaps using the v1.0 release?
I've tagged a new version.. Let me know if that works for you

**Comment by alx542** [comment]
There still seem to be problems caused by case.

For example, in ProviderServer.php there are calls like this 

        return Module::getModuleURL('openidProvider/user.php');

and I think this causes the page not to load.

**Comment by tvdijen** [comment]
What page are you trying to load and how?
I have set up the module and it appears to be working just fine now if I go to `https://idp.example.org/module.php/openidProvider/user.php`

**Comment by alx542** [comment]
I am running on centos 7 php 7.3 apache whm/cpanel 

I do composer require  ... can't seem to get dev-master to work. 

Without that it downloads version 1.1

I also tried the download zip of master 

...

I login as my test user or not  and as admin or not

I go to the authentication page
 
https://DOMAIN/module.php/core/frontpage_auth.php

and there is a link that says
not translated ({openidProvider:openidProvider:title_no_user}) 
the link points to: 
https://DOMAIN/module.php/openidProvider/user.php
But on load it redirects to:
https://DOMAIN/module.php/openidProvider/user.php/theconfigusername
that's my test user from my sp. 
or if I try 
https://DOMAIN/module.php/openidProvider/user.php
also blank page.



The log says 
Mar 26 17:11:11 simplesamlphp ERROR [5237166acd] SimpleSAML\Error\Exception: Error 1 - Call to a member function render() on null at /home/olnn/subdomains/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:514
Mar 26 17:11:11 simplesamlphp ERROR [5237166acd] Backtrace:
Mar 26 17:11:11 simplesamlphp ERROR [5237166acd] 2 /home/olnn/subdomains/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
Mar 26 17:11:11 simplesamlphp ERROR [5237166acd] 1 /home/olnn/subdomains/simplesamlphp/www/_include.php:25 (SimpleSAML_exception_handler)
Mar 26 17:11:11 simplesamlphp ERROR [5237166acd] 0 [builtin] (N/A)

If I check here and to a var_dump($this->twig_template) it returns null

 
    protected function getContents()
    {
        $this->twigDefaultContext();
        if ($this->controller) {
            $this->controller->display($this->data);
        }
        return $this->twig->render($this->twig_template, $this->data);
    }

**Comment by tvdijen** [comment]
Ah, you're relying on the old UI! That makes a difference..  I'll see to it that a 0.9 version is released that will work for you

**Comment by tvdijen** [comment]
v0.9.0 should work for you.. Please let me know how it goes
